// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import service "github.com/pastepaste/backend/service"

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// CreatePaste provides a mock function with given fields: _a0
func (_m *DB) CreatePaste(_a0 *service.Paste) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*service.Paste) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaste provides a mock function with given fields: _a0
func (_m *DB) GetPaste(_a0 string) (*service.Paste, error) {
	ret := _m.Called(_a0)

	var r0 *service.Paste
	if rf, ok := ret.Get(0).(func(string) *service.Paste); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Paste)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
